spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/outlay
    user: outlay
    password: outlay
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/outlay
    username: outlay
    password: outlay
  jooq:
    sql-dialect: postgres

  kafka:
    producer:
      bootstrap-servers: 'localhost:9092'
      client-id: 'clientId'
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    streams:
      application-id: 'streams-app'
